# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Windows 2019 with VS2019

steps:
- task: @1
  inputs:
    secureFile: 'signkey.snk'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: 'signkey.snk'
    TargetFolder: './private'

- task: PowerShell@2
  inputs:
    filePath: './tools/build.ps1'
    workingDirectory: './tools'
  displayName: 'Run the build script'
